nps:
  username: nps@sipc
  password: XXj85C
  ip: 49.232.223.89
  port: 8080

server:
  port: 50000

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/nps?userUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath:/mapper/*.xml

token:
  sign: Hanzoy@115private_NPS
  time: 60*60*24*7